### PR TITLE
fixes #12

### LINKED ISSUE #12: Spaceship game - Import Orbitron font from google fonts and use it in your game

### PR DESCRIPTION
**Pull request by ChaitanyaAgarwal72**
imported orbitron font from google fonts and used it.

### CODE REVIEW

**Comment by VibhorAgrawal2003** [comment]
This is good but the font should also be changed in the stylesheet. Try locating the css file and find where a font other than Orbitron is used and swap it.

**Comment by ChaitanyaAgarwal72** [comment]
Changed the font to Orbitron in style.css

**Comment by ChaitanyaAgarwal72** [comment]
I have changed the font in style.css in issue#12. Please review it, so that
I can get at least 10 points.
And also someone else did that too, but I did it before him.

**Comment by VibhorAgrawal2003** [comment]
Hi, thanks for being patient. We had some problems before with the file tree which led to the delay. Your commits are correct and we'll manually adjust the points on the leaderboard. Don't let our mishap discourage you, keep contributing as there are many more issues you can resolve.

**Pull request closed without merging**
