### PR TITLE
fixes #15

### LINKED ISSUE #15: Tetris - Make the tetromino falling speed dependent of level

### PR DESCRIPTION
**Pull request by vaibhavsijaria**
Speed of block fall is based on level (Increase with level). Solves #15

### CODE REVIEW

**Comment by Vaibhavi028** [comment]
While testing it, the speed of the falling block is actually getting reduced. Please go through the code once again.

**Comment by vaibhavsijaria** [comment]
@Vaibhavi028 sorry for confusion. I have fixed that. Please review it. Thank you

**Comment by Vaibhavi028** [comment]
The code fixes the issue but can you make the change in speed look more obvious by taking a major difference of 3 or 5

**Comment by vaibhavsijaria** [comment]
@Vaibhavi028 done

**Pull request merged**
