### PR TITLE
fixes #59

### LINKED ISSUE #59: Asteroids - Missing music in game

### PR DESCRIPTION
**Pull request by vaibhavsijaria**
added missing music from src directory to game. solved issue #59

### CODE REVIEW

**Comment by VibhorAgrawal2003** [comment]
The audio variables were not fully initialized. Try executing the game using index.html and see if it works correctly.

**Comment by vaibhavsijaria** [comment]
@VibhorAgrawal2003 It is working correctly for me. can you clarify what is correct intended behaviour

**Comment by VibhorAgrawal2003** [comment]
wait i'll check again

**Comment by VibhorAgrawal2003** [comment]
okay cool cool, i think i checked the wrong branch before lol, thanks for letting me know!

**Pull request merged**
